### ISSUE TITLE
Error when buffer has non-serializable vars

### ISSUE THREAD

**Issue by Milly** [shun/ddu-source-buffer#4]
Only reproduce with Vim, NOT Neovim.

Error occurs when buffer has non-serializable vars.

```
[denops] error: Uncaught (in worker "ddu") (in promise) BatchError: R
[denops]       throw new BatchError(errmsg, results);
[denops]             ^
[denops]     at DenopsImpl.batch (file:///tmp/vim-denops/denops.vim/denops/@denops/impl.ts:43:13)
[denops]     at async gather (https://deno.land/x/denops_std@v3.1.4/batch/gather.ts:91:10)
[denops]     at async get_buflist (file:///tmp/shun/ddu-source-buffer/denops/@ddu-sources/buffer.ts:63:53)
[denops]     at async Object.start (file:///tmp/shun/ddu-source-buffer/denops/@ddu-sources/buffer.ts:81:11)
[denops] error: Uncaught (in promise) Error: Unhandled error event in child worker.
[denops]     at Worker.#pollControl (deno:runtime/js/11_workers.js:168:21)
[denops] Server stopped (1). Restarting...
[denops] Server is restarted.
```

## Reproduction

Testing environment:
- Windows 10
- Vim 8.2.4732

1. Do `:let b:foo = {'bar': {-> 1}}`.
2. Call *ddu-source-buffer* with *ddu.vim*.

**Comment by Milly** [comment]
Sorry, I added testing environment.
